#----- SonarQube Analysis Setup
sonar.projectKey=rizkypandu91_golang-sonar-example
sonar.organization=rizkypandu91

sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=.coverage/coverage.out

# disable cpp
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
